spring:
  application:
    name: dubbo-auto-configuration-provider-demo

dubbo:
  scan:
    base-packages: com.momo.user.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://114.115.215.115:2181